### ISSUE TITLE
ModuleNotFoundError: No module named 'megatron.data.gpt_dataset'

### ISSUE THREAD

**Issue by liuxm117** [alibaba/Pai-Megatron-Patch#100]
您好，我在跑run_finetune_megatron_llama.sh时遇到这个问题，看了一下megatron/data下面确实没有gpt_dataset.py函数

**Comment by jerryli1981** [comment]
您好，问题出在您的Pai-Megatron-Patch文件夹下Megatron-LM-main文件夹为空，原因是您在执行$ git clone --recurse-submodules https://github.com/alibaba/Pai-Megatron-Patch.git的时候由于网络原因可能没有把submodules下载下来。

**Comment by jerryli1981** [comment]
您可以使用这个命令来获取对应的Megatron：wget https://easynlp-dev.oss-cn-zhangjiakou.aliyuncs.com/225247/Pai-Megatron-Patch/code/Megatron-LM-main.tgz

**Comment by liuxm117** [comment]
> 您可以使用这个命令来获取对应的Megatron：wget https://easynlp-dev.oss-cn-zhangjiakou.aliyuncs.com/225247/Pai-Megatron-Patch/code/Megatron-LM-main.tgz

这个是获取的哪个版本的Megatron-LM呢，是最新的吗

**Comment by liuxm117** [comment]
> 您好，问题出在您的Pai-Megatron-Patch文件夹下Megatron-LM-main文件夹为空，原因是您在执行$ git clone --recurse-submodules [https://github.com/alibaba/Pai-Megatron-Patch.git的时候由于网络原因可能没有把submodules下载下来。](https://github.com/alibaba/Pai-Megatron-Patch.git%E7%9A%84%E6%97%B6%E5%80%99%E7%94%B1%E4%BA%8E%E7%BD%91%E7%BB%9C%E5%8E%9F%E5%9B%A0%E5%8F%AF%E8%83%BD%E6%B2%A1%E6%9C%89%E6%8A%8Asubmodules%E4%B8%8B%E8%BD%BD%E4%B8%8B%E6%9D%A5%E3%80%82)

感谢，我看到会同时clone 23.04的megatron-lm，这个也是必须的吗

**Comment by jerryli1981** [comment]
> > 您可以使用这个命令来获取对应的Megatron：wget https://easynlp-dev.oss-cn-zhangjiakou.aliyuncs.com/225247/Pai-Megatron-Patch/code/Megatron-LM-main.tgz
> 
> 这个是获取的哪个版本的Megatron-LM呢，是最新的吗

对应main分支对应的commit的版本

**Comment by jerryli1981** [comment]
> > 您好，问题出在您的Pai-Megatron-Patch文件夹下Megatron-LM-main文件夹为空，原因是您在执行$ git clone --recurse-submodules [https://github.com/alibaba/Pai-Megatron-Patch.git的时候由于网络原因可能没有把submodules下载下来。](https://github.com/alibaba/Pai-Megatron-Patch.git%E7%9A%84%E6%97%B6%E5%80%99%E7%94%B1%E4%BA%8E%E7%BD%91%E7%BB%9C%E5%8E%9F%E5%9B%A0%E5%8F%AF%E8%83%BD%E6%B2%A1%E6%9C%89%E6%8A%8Asubmodules%E4%B8%8B%E8%BD%BD%E4%B8%8B%E6%9D%A5%E3%80%82)
> 
> 感谢，我看到会同时clone 23.04的megatron-lm，这个也是必须的吗

不是必须的，目前热门模型都已经支持了Megatron-LM-main
