### ISSUE TITLE
TransformerLayer.__init__() got an unexpected keyword argument 'apply_query_key_layer_scaling'

### ISSUE THREAD

**Issue by AGI-player** [alibaba/Pai-Megatron-Patch#104]
感谢作者大佬们的开源贡献哈。
基于Llama-2-13b-ms(https://modelscope.cn/models/modelscope/Llama-2-13b-ms/files)模型，适配之后，使用model_convertor.sh转换成功，如下图
<img width="197" alt="image" src="https://github.com/alibaba/Pai-Megatron-Patch/assets/99712469/1cf9d757-26c8-4854-97d6-fb3dcc177578">

再使用run_pretrain_megatron_llama.sh训练，指令如下：
sh run_pretrain_megatron_llama.sh dsw /git_model/Pai-Megatron-Patch 13B 1 8 1e-5 1e-6 1024 80 0 fp16 1 1 sel true false false true 100000 /llama2-datasets/wudao /Llama-2-13b-ms-to-megatron-tp1-pp1 100000000 10000 /output_megatron_llama2

报错，不匹配如下：
> building LLamaTokenizer tokenizer ...
Traceback (most recent call last):
  File "/git_model/Pai-Megatron-Patch/examples/llama2/pretrain_megatron_llama.py", line 126, in <module>
    pretrain(train_valid_test_datasets_provider, model_provider,
  File "/git_model/Pai-Megatron-Patch/megatron_patch/training.py", line 109, in pretrain
    model, optimizer, opt_param_scheduler = setup_model_and_optimizer(
  File "/git_model/Pai-Megatron-Patch/megatron_patch/training.py", line 327, in setup_model_and_optimizer
    model = get_model(model_provider_func, model_type)
  File "/git_model/Pai-Megatron-Patch/megatron_patch/training.py", line 256, in get_model
    model = model_provider_func(
  File "/git_model/Pai-Megatron-Patch/examples/llama2/pretrain_megatron_llama.py", line 38, in model_provider
    model = GPTModel(
  File "/git_model/Pai-Megatron-Patch/megatron_patch/model/llama2/gpt_model.py", line 71, in __init__
    self.language_model, self._language_model_key = get_language_model(
  File "/git_model/Pai-Megatron-Patch/megatron_patch/model/llama2/language_model.py", line 77, in get_language_model
    language_model = TransformerLanguageModel(
  File "/git_model/Pai-Megatron-Patch/megatron_patch/model/llama2/language_model.py", line 395, in __init__
    self.encoder = ParallelTransformer(
  File "/git_model/Pai-Megatron-Patch/megatron_patch/model/llama2/transformer.py", line 1630, in __init__
    [build_layer(i + 1 + offset) for i in range(self.num_layers)])
  File "/git_model/Pai-Megatron-Patch/megatron_patch/model/llama2/transformer.py", line 1630, in <listcomp>
    [build_layer(i + 1 + offset) for i in range(self.num_layers)])
  File "/git_model/Pai-Megatron-Patch/megatron_patch/model/llama2/transformer.py", line 1556, in build_layer
    return transformer_engine.pytorch.TransformerLayer(
TypeError: TransformerLayer.__init__() got an unexpected keyword argument 'apply_query_key_layer_scaling'

**Comment by larrylu0426** [comment]
> 感谢作者大佬们的开源贡献哈。 基于Llama-2-13b-ms([https://modelscope.cn/models/modelscope/Llama-2-13b-ms/files)模型，适配之后，使用model_convertor.sh转换成功，如下图](https://modelscope.cn/models/modelscope/Llama-2-13b-ms/files)%E6%A8%A1%E5%9E%8B%EF%BC%8C%E9%80%82%E9%85%8D%E4%B9%8B%E5%90%8E%EF%BC%8C%E4%BD%BF%E7%94%A8model_convertor.sh%E8%BD%AC%E6%8D%A2%E6%88%90%E5%8A%9F%EF%BC%8C%E5%A6%82%E4%B8%8B%E5%9B%BE) <img alt="image" width="197" src="https://private-user-images.githubusercontent.com/99712469/292739113-1cf9d757-26c8-4854-97d6-fb3dcc177578.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0NDgyOTEsIm5iZiI6MTcwNDQ0Nzk5MSwicGF0aCI6Ii85OTcxMjQ2OS8yOTI3MzkxMTMtMWNmOWQ3NTctMjZjOC00ODU0LTk3ZDYtZmIzZGNjMTc3NTc4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA1VDA5NDYzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2NTI2NGFjYjFlMjE1NDc1YTViYTU1MGQ3MDAzZGIxN2YwMzg0NGJmNGI3NDNmNmJkZWZiOWI2MDEzZDhmMTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WP5aYLm21Jpk6zR2gvluJ0ulwZbqiyaogLmtWY39co4">
> 
> 再使用run_pretrain_megatron_llama.sh训练，指令如下： sh run_pretrain_megatron_llama.sh dsw /git_model/Pai-Megatron-Patch 13B 1 8 1e-5 1e-6 1024 80 0 fp16 1 1 sel true false false true 100000 /llama2-datasets/wudao /Llama-2-13b-ms-to-megatron-tp1-pp1 100000000 10000 /output_megatron_llama2
> 
> 报错，不匹配如下：
> 
> > building LLamaTokenizer tokenizer ...
> > Traceback (most recent call last):
> > File "/git_model/Pai-Megatron-Patch/examples/llama2/pretrain_megatron_llama.py", line 126, in 
> > pretrain(train_valid_test_datasets_provider, model_provider,
> > File "/git_model/Pai-Megatron-Patch/megatron_patch/training.py", line 109, in pretrain
> > model, optimizer, opt_param_scheduler = setup_model_and_optimizer(
> > File "/git_model/Pai-Megatron-Patch/megatron_patch/training.py", line 327, in setup_model_and_optimizer
> > model = get_model(model_provider_func, model_type)
> > File "/git_model/Pai-Megatron-Patch/megatron_patch/training.py", line 256, in get_model
> > model = model_provider_func(
> > File "/git_model/Pai-Megatron-Patch/examples/llama2/pretrain_megatron_llama.py", line 38, in model_provider
> > model = GPTModel(
> > File "/git_model/Pai-Megatron-Patch/megatron_patch/model/llama2/gpt_model.py", line 71, in **init**
> > self.language_model, self._language_model_key = get_language_model(
> > File "/git_model/Pai-Megatron-Patch/megatron_patch/model/llama2/language_model.py", line 77, in get_language_model
> > language_model = TransformerLanguageModel(
> > File "/git_model/Pai-Megatron-Patch/megatron_patch/model/llama2/language_model.py", line 395, in **init**
> > self.encoder = ParallelTransformer(
> > File "/git_model/Pai-Megatron-Patch/megatron_patch/model/llama2/transformer.py", line 1630, in **init**
> > [build_layer(i + 1 + offset) for i in range(self.num_layers)])
> > File "/git_model/Pai-Megatron-Patch/megatron_patch/model/llama2/transformer.py", line 1630, in 
> > [build_layer(i + 1 + offset) for i in range(self.num_layers)])
> > File "/git_model/Pai-Megatron-Patch/megatron_patch/model/llama2/transformer.py", line 1556, in build_layer
> > return transformer_engine.pytorch.TransformerLayer(
> > TypeError: TransformerLayer.**init**() got an unexpected keyword argument 'apply_query_key_layer_scaling'

transformer engine的版本不匹配，从v1.0开始transformer engine中TransformerLayer的参数就移除了apply_query_key_layer_scaling这个参数

**Comment by AGI-player** [comment]
> > 感谢作者大佬们的开源贡献哈。 基于Llama-2-13b-ms([https://modelscope.cn/models/modelscope/Llama-2-13b-ms/files)模型，适配之后，使用model_convertor.sh转换成功，如下图](https://modelscope.cn/models/modelscope/Llama-2-13b-ms/files)%E6%A8%A1%E5%9E%8B%EF%BC%8C%E9%80%82%E9%85%8D%E4%B9%8B%E5%90%8E%EF%BC%8C%E4%BD%BF%E7%94%A8model_convertor.sh%E8%BD%AC%E6%8D%A2%E6%88%90%E5%8A%9F%EF%BC%8C%E5%A6%82%E4%B8%8B%E5%9B%BE) <img alt="image" width="197" src="https://private-user-images.githubusercontent.com/99712469/292739113-1cf9d757-26c8-4854-97d6-fb3dcc177578.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0NDgyOTEsIm5iZiI6MTcwNDQ0Nzk5MSwicGF0aCI6Ii85OTcxMjQ2OS8yOTI3MzkxMTMtMWNmOWQ3NTctMjZjOC00ODU0LTk3ZDYtZmIzZGNjMTc3NTc4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA1VDA5NDYzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2NTI2NGFjYjFlMjE1NDc1YTViYTU1MGQ3MDAzZGIxN2YwMzg0NGJmNGI3NDNmNmJkZWZiOWI2MDEzZDhmMTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WP5aYLm21Jpk6zR2gvluJ0ulwZbqiyaogLmtWY39co4">
> > 再使用run_pretrain_megatron_llama.sh训练，指令如下： sh run_pretrain_megatron_llama.sh dsw /git_model/Pai-Megatron-Patch 13B 1 8 1e-5 1e-6 1024 80 0 fp16 1 1 sel true false false true 100000 /llama2-datasets/wudao /Llama-2-13b-ms-to-megatron-tp1-pp1 100000000 10000 /output_megatron_llama2
> > 报错，不匹配如下：
> > > building LLamaTokenizer tokenizer ...
> > > Traceback (most recent call last):
> > > File "/git_model/Pai-Megatron-Patch/examples/llama2/pretrain_megatron_llama.py", line 126, in
> > > pretrain(train_valid_test_datasets_provider, model_provider,
> > > File "/git_model/Pai-Megatron-Patch/megatron_patch/training.py", line 109, in pretrain
> > > model, optimizer, opt_param_scheduler = setup_model_and_optimizer(
> > > File "/git_model/Pai-Megatron-Patch/megatron_patch/training.py", line 327, in setup_model_and_optimizer
> > > model = get_model(model_provider_func, model_type)
> > > File "/git_model/Pai-Megatron-Patch/megatron_patch/training.py", line 256, in get_model
> > > model = model_provider_func(
> > > File "/git_model/Pai-Megatron-Patch/examples/llama2/pretrain_megatron_llama.py", line 38, in model_provider
> > > model = GPTModel(
> > > File "/git_model/Pai-Megatron-Patch/megatron_patch/model/llama2/gpt_model.py", line 71, in **init**
> > > self.language_model, self._language_model_key = get_language_model(
> > > File "/git_model/Pai-Megatron-Patch/megatron_patch/model/llama2/language_model.py", line 77, in get_language_model
> > > language_model = TransformerLanguageModel(
> > > File "/git_model/Pai-Megatron-Patch/megatron_patch/model/llama2/language_model.py", line 395, in **init**
> > > self.encoder = ParallelTransformer(
> > > File "/git_model/Pai-Megatron-Patch/megatron_patch/model/llama2/transformer.py", line 1630, in **init**
> > > [build_layer(i + 1 + offset) for i in range(self.num_layers)])
> > > File "/git_model/Pai-Megatron-Patch/megatron_patch/model/llama2/transformer.py", line 1630, in
> > > [build_layer(i + 1 + offset) for i in range(self.num_layers)])
> > > File "/git_model/Pai-Megatron-Patch/megatron_patch/model/llama2/transformer.py", line 1556, in build_layer
> > > return transformer_engine.pytorch.TransformerLayer(
> > > TypeError: TransformerLayer.**init**() got an unexpected keyword argument 'apply_query_key_layer_scaling'
> 
> transformer engine的版本不匹配，从v1.0开始transformer engine中TransformerLayer的参数就移除了apply_query_key_layer_scaling这个参数

好的，感谢。
