### ISSUE TITLE
fp8精度权重转换

### ISSUE THREAD

**Issue by liuxm117** [alibaba/Pai-Megatron-Patch#108]
您好，想问一下，我使用hf2te.sh转换llama权重之后做了微调，得到的megatron权重怎么再转回为hf的格式呢，有可以推荐的方法吗

**Comment by jerryli1981** [comment]
您好，请pull下最新的代码，按照Quick Start的ReadMe中的转换流程再试下

**Comment by jerryli1981** [comment]
需要使用mcore的训练训练才能开启FP8训练
