### ISSUE TITLE
Mixtral model convert no "convert_checkpoint_from_megatron_to_transformers" function

### ISSUE THREAD

**Issue by cdj0311** [alibaba/Pai-Megatron-Patch#116]
hi,
The script Pai-Megatron-Patch/toolkits/model_checkpoints_convertor/mixtral/model_convertor.sh give a parameter "--convert_checkpoint_from_megatron_to_transformers", however, these no "convert_checkpoint_from_megatron_to_transformers" function in checkpoint_reshaping_and_interoperability.py.

**Comment by ftgreat** [comment]
+1
