### ISSUE TITLE
Qwen 72B 中 megatron 和 huggingface 的不一致

### ISSUE THREAD

**Issue by chaochen99** [alibaba/Pai-Megatron-Patch#118]
在https://github.com/alibaba/Pai-Megatron-Patch/blob/main/examples/qwen/run_pretrain_megatron_qwen.sh 中，rotary-seq-len-interpolation-factor=4， RotaryEmbedding的base=10000

但是在huggingface 的config 中RotaryEmbedding 的base=1000000

请问那种方式更贴合预训练的配置？

**Comment by lwmlyy** [comment]
需要和huggingface中的config对齐
