### ISSUE TITLE
qwen 7B 增量预训练，模型加载完，卡在 dataloader 部分, seq_length=0

### ISSUE THREAD

**Issue by songyingxin** [alibaba/Pai-Megatron-Patch#121]
一直卡在数据处理位置，处理时间很长，3m数据十分钟都没处理完，debug到此处的 seq_length=0 ：
![image](https://github.com/alibaba/Pai-Megatron-Patch/assets/13884292/cc32413b-6ed6-4a37-88de-5e0d037a6139)
![image](https://github.com/alibaba/Pai-Megatron-Patch/assets/13884292/41248fc0-a441-4b9f-9b16-8e9513b6bb18)

![image](https://github.com/alibaba/Pai-Megatron-Patch/assets/13884292/d2dfa14e-76f4-4ca6-b1a6-ae2e9ae5d893)

**Comment by lwmlyy** [comment]
训练配置方便发一下吗 多机多卡训练吗

**Comment by jerryli1981** [comment]
您好，请参考Quick Start中qwen的流程再尝试下
