### ISSUE TITLE
RuntimeError: The size of tensor a (120) must match the size of tensor b (119) at non-singleton dimension 2

### ISSUE THREAD

**Issue by wangxiang2713** [alibaba/Pai-Megatron-Patch#131]
examples/llama2/run_finetune_megatron_llama.sh, 执行报错:
  File "/mnt/dolphinfs/hdd_pool/docker/user/hadoop-hdp/wangxiang27/code/Pai-Megatron-Patch/megatron_patch/model/llama2/rotary_pos_embedding.py", line 91, in apply_rotary_pos_emb
    q_embed = (q * cos) + (rotate_half(q) * sin)
RuntimeError: The size of tensor a (120) must match the size of tensor b (119) at non-singleton dimension 2

配置: dp = 2, pp = 2, tp = 2
#sh run_finetune_megatron_llama.sh dsw ../.. 7B 1 1e-5 1e-6 120 120 0 bf16 2 2 sel true false false false  /mnt/llama2-datasets/alpaca_data.json /mnt/llama2-datasets/alpaca_data.json /mnt/llama2-ckpts/Llama-2-7b-hf-to-mg-tp2-pp2/ 2 /mnt/output_patch_test

**Comment by wangxiang2713** [comment]
I found with pp, stage 2 should receive hidden_states with shape [79, 1, 4096], but receive hidden_states with shape [64, 1, 4096]

**Comment by wangxiang2713** [comment]
I guss, for pp1 input_ids seq_length = 119, but pp2 think input_ids seq_length = 120

**Comment by jerryli1981** [comment]
您好，烦请重新pull下最新的代码，按照Quick Start的指引再测试下，谢谢
