### ISSUE TITLE
模型训练所需显存显著高于MegatronDeepspeed框架

### ISSUE THREAD

**Issue by Hades-Z** [alibaba/Pai-Megatron-Patch#135]
在使用咱们框架训练Yi6B模型时，我遇到了以下的情况：
        同样使用4块A800显卡和长度填充到6000token的训练数据，做无数据并行、无模型并行、4张量并行的分布式训练，在MegatronDeepspeed框架micro-batch-size可以设置为8，而在咱们的框架中仅能设置为1，请问这种资源消耗情况正常吗？
有何方法能在尽量保证训练效果的同时减少显存占用吗？

**Comment by jerryli1981** [comment]
MegatronDeepspeed框架貌似使用的是zero显存优化器，zero的降显存机制和Megatron中的distributed optimizer不太一样，一般模型越大，megatron的吞吐加速越显著
