### ISSUE TITLE
支持rwkv

### ISSUE THREAD

**Issue by BBuf** [alibaba/Pai-Megatron-Patch#15]
请问一下可以支持rwkv模型训练吗？https://github.com/BlinkDL/RWKV-LM

**Comment by jerryli1981** [comment]
您好，我们先调研下RWKV-LM

**Comment by BBuf** [comment]
> 您好，我们先调研下RWKV-LM
好的

**Comment by jerryli1981** [comment]
抱歉，这个模型暂时没有进一步支持的计划
