### ISSUE TITLE
代码在本地单机上是否能用

### ISSUE THREAD

**Issue by smartparrot** [alibaba/Pai-Megatron-Patch#150]

**Comment by smartparrot** [comment]
ok. 
还有这个get_args的实现路径在哪呢，是在megatron_lm文件下吗，没有找到确切的实现函数
from megatron import get_args

**Comment by jerryli1981** [comment]
1. get_args是在Megatron LM里面实现的, 具体在Megatron/global_variable.py里面
2. 并不需要，因为在启动脚本中已经指定了MegatronLM的位置

**Comment by LuYutt** [comment]
你好，我想问一下，要是本地，环境torch版本deepspeed有限制吗？

**Comment by jerryli1981** [comment]
> 你好，我想问一下，要是本地，环境torch版本deepspeed有限制吗？

没有限制
