### ISSUE TITLE
关于超出序列长度截断

### ISSUE THREAD

**Issue by HPRCEST** [alibaba/Pai-Megatron-Patch#154]
请问一下，现在我在这个框架上进行继续预训练，序列长度设为4096，但是有很多数据都超过了这个长度。框架具有自动拼接的功能吗？还是我需要手动把较长的数据分割，较短的数据拼接到一起？

**Comment by jerryli1981** [comment]
您好，继续预训练推荐使用idxmap格式数据 （https://github.com/alibaba/Pai-Megatron-Patch/blob/main/toolkits/pretrain_data_preprocessing/run_make_pretraining_dataset.sh），然后框架具备自动拼接的能力，通过eod_id来划分文档间隔。

**Comment by yanyc428** [comment]
想请问一下这个逻辑具体实现的代码是哪个文件呢
