### ISSUE TITLE
您好，请问什么时候可以支持baichuan2呀～

### ISSUE THREAD

**Issue by zhangbin1997** [alibaba/Pai-Megatron-Patch#16]
比如在megatron中支持max-z loss， normhead等，还有支持baichuan2中的alibi + flash attention 2的结合。
另外，因为我之前也实现了megatron中的llama模型实现，其中huggingface的llama权重中没有model.layers.X.post_attention_layernorm.bias，并且post_attention_layernorm 应该是RMSNorm，而不是LayerNorm ～

**Comment by jerryli1981** [comment]
您好，感谢提出Issue
1. 当前版本中的百川已经支持alibi + flash attention 2的结合
2. 我们对bias初始化为0，好让模型能够使用速度更快的LayerNorm。采用RMSNorm和LayerNorm不会影响继续预训练/微调的loss曲线

**Comment by jerryli1981** [comment]
huggingface上的baichuan-2的实现两天前刚刚放出，我们正在接入中，预计下周可以push到github

**Comment by jerryli1981** [comment]
百川2已经支持，烦请适用或者进群技术交流
