### ISSUE TITLE
how to install the training envirenments?

### ISSUE THREAD

**Issue by alphanlp** [alibaba/Pai-Megatron-Patch#163]

**Comment by jerryli1981** [comment]
docker pull dsw-registry.cn-wulanchabu.cr.aliyuncs.com/pai/pytorch-training:23.12-gpu-py310-cu123-ubuntu22.04-megatron-patch-llm

**Comment by tjoymeed** [comment]
Given today is May 2025, where to pull the docker image? Any new updates?
