### ISSUE TITLE
Will Pai-Megatron-Patch support PEFT and quantization?

### ISSUE THREAD

**Issue by haolin-nju** [alibaba/Pai-Megatron-Patch#164]
Thanks for your hard work and the contribution! I'm wondering if Pai-Megatron-Patch will support PEFT (Parameter Efficient Fine-Tuning) techniques such as LoRA, as well as quantization techniques such as QLoRA, GPT-Q, or AWQ in the near future? It would be of great help. Thanks a lot!

**Comment by lwmlyy** [comment]
Thanks for your interest!

Unfortunately, we do not have plans for peft and quantization in the near future.
