### ISSUE TITLE
Please update Falcon :)

### ISSUE THREAD

**Issue by pharaouk** [alibaba/Pai-Megatron-Patch#179]

**Comment by jerryli1981** [comment]
you mean update Falcon in Quick Start?

**Comment by pharaouk** [comment]
yes like llama and mistral, would like to see falcon up to date, including moe functionalities that you are implementing

**Comment by pharaouk** [comment]
the falcon code is out of date completely 

for instance:

```from megatron_patch.data.finetune_dataset import FalconDataset```

I don't see ```finetune_dataset``` there, neither ```FalconDataset``` anywhere

**Comment by jerryli1981** [comment]
ok，btw，Is falcon hot again recently? Or why you need falcon instead of llama2, mistral or qwen1.5?

**Comment by pharaouk** [comment]
```from megatron_patch.data.pretrain_dataset import \
    build_pretrain_falcon_datasets_from_original, build_pretrain_falcon_datasets_from_idxmap```

this is nonexistent. Basically all the Falcon code is questionable rn

**Comment by pharaouk** [comment]
> ok，btw，Is falcon hot again recently? Or why you need falcon instead of llama2, mistral or qwen1.5?

good question, old falcon is not necessarily competitive. can talk in DM for why I'm requesting updates.

**Comment by jerryli1981** [comment]
> > ok，btw，Is falcon hot again recently? Or why you need falcon instead of llama2, mistral or qwen1.5?
> 
> good question, old falcon is not necessarily competitive. can talk in DM for why I'm requesting updates.

Sure, you can go into our dingding talk group and add me, then we can talk
