### ISSUE TITLE
Mistral持续预训练的脚本是否支持pp>=2？

### ISSUE THREAD

**Issue by kobayashikanna01** [alibaba/Pai-Megatron-Patch#183]
我在使用最新版的Pai-Megatron-Patch对Mistral-7b-v0.1进行持续预训练。

当我设置tp=1/pp=2或者tp=1/pp=4或者tp=2/pp=2时，均出现了下述错误：
```
File "/my_workspace/Pai-Megatron-Patch/megatron_patch/model/mistral/modeling_attn_mask_utils.py", line 198, in _prepare_4d_causal_attention_mask    
attention_mask, input_shape[-1], key_value_length, dtype=inputs_embeds.dtype                                                                   AttributeError: 'NoneType' object has no attribute 'dtype'
```

我的机器有8块显卡，我在_prepare_4d_causal_attention_mask函数内打印了：print(attention_mask.device，input_shape，inputs_embeds)
得到如下结果:
```
cuda:0 (1, 2048) 一个Tensor
cuda:1 (1, 2048) 一个Tensor
cuda:2 (1, 2048) 一个Tensor
cuda:3 (1, 2048) 一个Tensor
cuda:0 (1, 2048) None
cuda:1 (1, 2048) None
cuda:2 (1, 2048) None
cuda:3 (1, 2048) None
```

我自始至终未能看到来自cuda:4~cuda:7的输出。

当我设置tp=2 or 4/pp=1时，不会遇到这个错误。

我希望确认一下，目前Pai-Megatron-Patch是否能支持在pp>=2的情况下训练Mistral-7b？

**Comment by jerryli1981** [comment]
我刚测试了下，我跑如下的PP=2的convert脚本并没有报错，您是不是再参考下QS里面的流程
sh model_convertor.sh ../../../ /mnt/mistral-ckpts/Mistral-7B-v0.1 /mnt/mistral-ckpts/Mistral-7B-v0.1-tp4-pp2 4 2 mistral-7b 0 false

**Comment by jerryli1981** [comment]
PP>1问题已修复，烦请pull下最新的代码，这是PR，烦请Review：https://github.com/alibaba/Pai-Megatron-Patch/pull/185
