### ISSUE TITLE
llama3 报错

### ISSUE THREAD

**Issue by yangzhipeng1108** [alibaba/Pai-Megatron-Patch#210]
cd /workspace/Pai-Megatron-Patch/examples/llama3
sh run_pretrain_megatron_llama.sh  \
dsw  \
../../ \
8B   \
1    \
8 \
1e-5   \
1e-6   \
2048  \
2048  \
256  \
bf16  \
2   \
1  \
sel  \
true   \
true  \
true   \
true   \
100000  \
/workspace/data/oscar-en-10k-meg-llama_text_document  \
/workspace/model_ckpts/Meta-Llama-3-8B-to-megatron-tp2-pp1 \
100000000   \
10000   \
/workspace/output_megatron_llama3
![image](https://github.com/alibaba/Pai-Megatron-Patch/assets/33448441/431b0b43-1971-485d-a61e-28a2c0e55c5b)

**Comment by jerryli1981** [comment]
您好，收到，脚本内外网同步有问题，已修复：https://github.com/alibaba/Pai-Megatron-Patch/pull/211
然后刚又按照ReadMe （https://github.com/alibaba/Pai-Megatron-Patch/blob/main/examples/llama3/README.md#Megatron-LM-Dense%E6%A8%A1%E5%9E%8B%E8%AE%AD%E7%BB%83%E6%B5%81%E7%A8%8B）重新测试下能跑通，辛苦再试试

**Comment by yangzhipeng1108** [comment]
厉害
