### ISSUE TITLE
我可以用最新的 Megatron 和 Grouped GEMM 训练一个 MOE 模型吗？我尝试了你转换的检查点，但它没有工作，我应该做些不同的事情吗？

### ISSUE THREAD

**Issue by shamanez** [alibaba/Pai-Megatron-Patch#213]
这个 PR 表示已经修复了，但我不确定我们是否可以在最新的 Megatron 中使用分组 GEMM。

https://github.com/alibaba/Pai-Megatron-Patch/pull/196

**Comment by jerryli1981** [comment]
可以使用GEMM，请参考：https://github.com/alibaba/Pai-Megatron-Patch/blob/main/examples/llama3/pretrain_llama.py#L57

**Comment by hwdef** [comment]
@jerryli1981 模型转换支持grouped-gemm吗
