### ISSUE TITLE
Megatron-Core-MoE

### ISSUE THREAD

**Issue by yangzhipeng1108** [alibaba/Pai-Megatron-Patch#216]
sh run_pretrain_mcore_qwen.sh  \
dsw  \
../../ \
0.5B   \
1    \
8 \
1e-5   \
1e-6   \
128  \
128  \
293   \
bf16  \
1   \
1  \
sel  \
true   \
false  \
false   \
false   \
true \
100000  \
/workspace/data/wudao_qwenbpe_text_document  \
/workspace/model_ckpts/Qwen1.5-0.5B-hf-to-mcore-tp1-pp1-ep1-exp8   \
100000000   \
10000   \
/mnt/output_mcore_qwen
![image](https://github.com/alibaba/Pai-Megatron-Patch/assets/33448441/e26f1771-acce-4ed3-b2f2-49f1897f0f5c)

**Comment by jerryli1981** [comment]
您好，由于patch不能修改Megatron-LM-240405中的任何代码，因此您需要手动将Megatron-LM-240405/megatron/training/checkpointing.py的718行的strict=False。同时这个提示给您一次检查ckpt对齐的机会，也就是说仅出现._extra_state是合理的，如果错误日志中再出现其他算子那就不正常了

**Comment by jerryli1981** [comment]
另外您也可以进钉钉群沟通，这样处理issue可能更快速

**Comment by yangzhipeng1108** [comment]
好的，谢谢
