### ISSUE TITLE
llama3增量预训练时张量维度不匹配

### ISSUE THREAD

**Issue by gllary** [alibaba/Pai-Megatron-Patch#224]
下载了最新的代码库，在进行llama3增量预训练时遇到如下报错：
 size mismatch for weight: copying a param with shape torch.Size([16032, 8192]) from checkpoint, the shape in current model is torch.Size([16000, 8192]).self.language_model.load_state_dict(state_dict, strict=strict)

求助大佬！

**Comment by lwmlyy** [comment]
extra_vocab_size设置成256试试
