### ISSUE TITLE
多机llama3 pt训练报错

### ISSUE THREAD

**Issue by bsyonline** [alibaba/Pai-Megatron-Patch#226]
我测试llama3 pt训练，指定数据集
--train-data-path 1 /dataset/llama3//train_t1/ppl-partition0_0000 1 /dataset/llama3//train_t1/ppl-partition1_0000 1 /dataset/llama3//train_t1/ppl-partition2_0000 1 /dataset/llama3//train_t1/ppl-partition3_0000 1 /dataset/llama3//train_t1/ppl-partition4_0000
--valid-data-path 1 /dataset/llama3//ch_val_t1/ppl-partition0_0000 1 /dataset/llama3//ch_val_t1/ppl-partition1_0000 1 /dataset/llama3//ch_val_t1/ppl-partition2_0000 1 /dataset/llama3//ch_val_t1/ppl-partition3_0000 1 /dataset/llama3//ch_val_t1/ppl-partition4_0000

单机正常运行，多机报错
raise pickle.UnpicklingError(raise pickle.UnpicklingError(
_pickle_pickle..UnpicklingErrorUnpicklingError: : Failed to interpret file '/dataset/llama3//train_t1/index-cache/ebe6e4d84ac77bd30d78014fac52a4bd_shuffle_idx.npy' as a pickleFailed to interpret file '/dataset/llama3//train_t1/index-cache/ebe6e4d84ac77bd30d78014fac52a4bd_shuffle_idx.npy' as a pickle

请问如何解决？

**Comment by lwmlyy** [comment]
单机先运行一次，然后将生成的数据文件*.npy和*.index拷贝至其它机器，再运行多机任务。

**Comment by bsyonline** [comment]
> 单机先运行一次，然后将生成的数据文件*.npy和*.index拷贝至其它机器，再运行多机任务。

感谢回复。
我按照这种方式试了一下，还是会有上述问题。我单机正常开始训练就停掉了，然后换成多机运行。

我看源码里这个文件名的生成
# Filename of the index mappings.
    desc = "GPT Dataset\n\n"
    desc += f"Data prefix {data_prefix}\n"
    desc += f"Dataset name {name}\n"
    desc += f"Number of samples {num_samples}\n"
    desc += f"Sequence length {seq_length}\n"
    desc += f"Random seed {seed}\n"
    desc += f"Split {splits_string}\n"
    desc_hash = hashlib.md5(desc.encode('utf-8')).hexdigest()
    desc_filename = desc_hash + ".dsc"
    doc_idx_filename = desc_hash + '_doc_idx.npy'
    sample_idx_filename = desc_hash + '_sample_idx.npy'
    shuffle_idx_filename = desc_hash + '_shuffle_idx.npy'
num_samples是每次都改变的，也就是假如这个方法可以的话，也是要单机跑完所有的samples，多机跑才OK，我这样理解对么？

另外先生成一次npy文件再多机跑根本原因是什么？从根本上如何解决呢？

**Comment by lwmlyy** [comment]
只要生成数据即可。这里的根本原因是多机任务没有使用同一个文件系统。

**Comment by jerryli1981** [comment]
您好，先试试看qwen1.5的多机分布式是否有问题

**Comment by bsyonline** [comment]
> 您好，先试试看qwen1.5的多机分布式是否有问题

您好，刚试了一下Qwen1.5 0.5B多机也会报这个错误，单机正常。

**Comment by lwmlyy** [comment]
如果每个数据集的权重都是1的话，建议合并成一个完整的mmap文件，多机就不会出错了。
如果一定要多个数据集，则参考上面的操作。

**Comment by bsyonline** [comment]
> 只要生成数据即可。这里的根本原因是多机任务没有使用同一个文件系统。

我使用的是共享存储，应该算是一个文件系统吧？
