### ISSUE TITLE
spelling mistake in example ReadMe

### ISSUE THREAD

**Issue by liddk** [alibaba/Pai-Megatron-Patch#229]
https://github.com/alibaba/Pai-Megatron-Patch/blob/main/examples/qwen1_5/README.md#%E6%95%B0%E6%8D%AE%E9%9B%86%E5%92%8C%E6%A8%A1%E5%9E%8B%E4%B8%8B%E8%BD%BD
wgt->wget
![image](https://github.com/alibaba/Pai-Megatron-Patch/assets/8046546/cb985480-b1b7-4541-b94c-e5dc8b3dce6e)

**Comment by jerryli1981** [comment]
Thank you very much. Already fixed, please review: https://github.com/alibaba/Pai-Megatron-Patch/pull/231
