### ISSUE TITLE
Needs requirements.txt

### ISSUE THREAD

**Issue by miangangzhen** [alibaba/Pai-Megatron-Patch#23]
Hi, would you release requirements.txt for this project?
I have meet Megatron and flash-attn version problem.

**Comment by haibaoY** [comment]
+1

**Comment by jerryli1981** [comment]
Hi fellows, you can go into dingtalk group and get docker image. Then you can create container via that image

**Comment by jerryli1981** [comment]
requirements.txt is uploaded, please check it out
