### ISSUE TITLE
MegaBlocks训练

### ISSUE THREAD

**Issue by zhanjiqing** [alibaba/Pai-Megatron-Patch#232]
@jerryli1981 您好，感谢在Pai上的工作。看您最近引入了MegaBlocks来进行MoE训练，不知道有没有对比过和MCore的速度对比情况？我在使用的过程遇到了几个问题，不知道您有没有好的建议：
- 因为不能使用DO，所以在训练8x7B的模型的时候发现很占显存，4机A800没跑起来，可能是我哪里使用方式有问题？
- 因为显存占用大，所以设置AC=full，但是又会提示不是is_first_microbatch的问题？

**Comment by jerryli1981** [comment]
您好，感谢关注。我们最新把最新的MoE模型比如DeepSeek-V2和Qwen2的MoE都进行了Mcore的实现，建议您先试试Mcore的实现哈
