### ISSUE TITLE
qwen moe模型训练脚本的参数是不是不对？能提供正确的训练脚本吗

### ISSUE THREAD

**Issue by jianhai0527** [alibaba/Pai-Megatron-Patch#234]
<img width="865" alt="image" src="https://github.com/alibaba/Pai-Megatron-Patch/assets/7888850/5626edb0-1de2-4849-ba68-6c54c9cd7ae1">

RT

**Comment by jerryli1981** [comment]
您好，ReadMe已更新，烦请CR：https://github.com/alibaba/Pai-Megatron-Patch/pull/239

![image](https://github.com/alibaba/Pai-Megatron-Patch/assets/9262007/03229b2c-702c-4c9f-960f-dae2a02e7392)
