### ISSUE TITLE
Support transformer-engine version after 0.9.0

### ISSUE THREAD

**Issue by Hsuxu** [alibaba/Pai-Megatron-Patch#235]
`apply_query_key_layer_scaling` and `attention_softmax_in_fp32`  are used in  [LLaMA2](https://github.com/alibaba/Pai-Megatron-Patch/blob/main/megatron_patch/model/llama2/transformer.py#L1572),  while deprecated in [transforme-enigne release note](https://docs.nvidia.com/deeplearning/transformer-engine-releases/release-0.9.0/release-notes/index.html#deprecated-features)
In the latest version, these two arguments are removed.

**Comment by jerryli1981** [comment]
收到，感谢您的建议。貌似我们无法直接更新transformer-engine，我们都是更新Megatron-LM版本的。您说的这个问题我还没有完全get到，方便进群at我交流下吗？
