### ISSUE TITLE
fintune模型

### ISSUE THREAD

**Issue by QingqingSun-Bao** [alibaba/Pai-Megatron-Patch#242]
请教一个问题：
 得到微调后的base模型，需要合并权重文件后做切分才能做fintune吗？还是直接做fintue就可以不需要操作权重文件

**Comment by QingqingSun-Bao** [comment]
或者说当前的项目不支持tp>1的fintune？

**Comment by jerryli1981** [comment]
您好，当前代码支持tp>1的微调的，用的就是和预训练一样的代码，可以参考下最新的qwen2的实现
