### ISSUE TITLE
日志中输出的参数总量是不是有问题呢

### ISSUE THREAD

**Issue by jianhai0527** [alibaba/Pai-Megatron-Patch#246]
我用的是 Qwen1.5-MoE-A2.7B模型，日志中输出的总参数量是 50B
Number of parameters in transformer layers in billions:  50.23
Number of parameters in embedding layers in billions: 0.62
Total number of parameters in billions: 50.85

**Comment by jerryli1981** [comment]
嗯，日志输出可能有问题。按照https://qwenlm.github.io/blog/qwen-moe/ 给出的解释，Qwen1.5-MoE-A2.7B总共应该有14B的参数，不应该是50B
