### ISSUE TITLE
[QUESTION] sft阶段数据长短不一，大量padding如何高效训练。

### ISSUE THREAD

**Issue by oymzysmwe224** [alibaba/Pai-Megatron-Patch#251]
在指令微调阶段由于数据长短不一，全部padding到max_seq_len 会导致大量的无用计算，有啥办法可以高效训练的方式么？
我看到get_batch_data 里面有个逻辑产生的是二维的attention_mask，是否可以通过将多条样本拼到一起，然后通过分段的attention_mask来实现高效训练？

**Comment by jerryli1981** [comment]
您好，可以使用sequence packing技术，这个在llama factory中有实现，可以尝试接入下，谢谢
