### ISSUE TITLE
tokenize with qwen2tokenizer in megatron_patch/tokenizer/__init__.py

### ISSUE THREAD

**Issue by lclkent** [alibaba/Pai-Megatron-Patch#252]
I was kind of lost with the preprocess data tool. XD
Why wrap the qwen2tokenizer with MegatronTokenizer? why not directly use the huggingface tokenizer? And btw, I wasn't able to find a class named MegatronTokenizer in the megatron project. I doubt a code version mismatch, can someone explain this?

**Comment by jerryli1981** [comment]
https://github.com/alibaba/Pai-Megatron-Patch/blob/main/megatron_patch/tokenizer/__init__.py#L171

**Comment by jerryli1981** [comment]
hi，due to idxmap dataset in latest Megatron-LM, we have to wrap class _Qwen2Tokenizer(MegatronTokenizer):
