### ISSUE TITLE
deepseek-v2实现的有问题，不能支持tp>1的情况

### ISSUE THREAD

**Issue by 154912369** [alibaba/Pai-Megatron-Patch#255]
感谢大佬支持的deepseek-v2的megatron实现！
然后，我说一下我跑实验时候的问题，在做线性变化的时候需要使用了ColumnParallelLinear，这个类没法支持context parallel，这导致没法跑236B版本的deepseek-v2-chat。

**Comment by jerryli1981** [comment]
您好，支持TP>1情况下的sequence parallel的。或者进钉钉群加我详细聊下？

**Comment by jerryli1981** [comment]
deepseek-v2-lite模型是能够支持TP>1且loss收敛和TP=1是一样的，所以您的issue标题的表述我不是很理解，还是进群直接at我沟通吧？

**Comment by jerryli1981** [comment]
hi, 您好，进钉钉群了嘛？或者直接加我微信：jerryli1981，咱们对齐下技术细节哈谢谢！

**Comment by 154912369** [comment]
> 您好，支持TP>1情况下的sequence parallel的。或者进钉钉群加我详细聊下？

这是mixtral的实现，里面用的TEColumnParallelLinear
![截屏2024-06-12 11 23 19](https://github.com/alibaba/Pai-Megatron-Patch/assets/47050695/824ea7b6-7be6-4f5b-9632-74d56845b2fa)
这是qwen的实现，里面用的是ColumnParallelLinear
![截屏2024-06-12 11 25 27](https://github.com/alibaba/Pai-Megatron-Patch/assets/47050695/00c590a2-4b91-4cf5-b5ea-d112d126aa54)
但是ColumnParallelLinear是不支持tp>1的sequence parallel。
![截屏2024-06-12 11 29 16](https://github.com/alibaba/Pai-Megatron-Patch/assets/47050695/e085575a-4c15-4ca5-8108-67d3330e9d82)
另外，TEDotProductAttention怎么没用，用的自己实现的attention，这也是有问题的。
