### ISSUE TITLE
Mixtral: AssertionError: (RMSNorm) is not supported in FusedLayerNorm

### ISSUE THREAD

**Issue by Treemann** [alibaba/Pai-Megatron-Patch#257]
Hi, I followed [this instruction](https://github.com/alibaba/Pai-Megatron-Patch/blob/main/examples/mistral/README.md#megatron-core-moe%E6%A8%A1%E5%9E%8B%E6%A0%BC%E5%BC%8F%E8%BD%AC%E6%8D%A2) to convert Mixtral-8x7B and then pretrained it  with examples/mistral/run_pretrain_mcore_mistral.sh. I got the following error which indicates that `(RMSNorm) is not supported in FusedLayerNorm`. Is there any way to solve this issue?

> INFO:datasets:PyTorch version 2.4.0a0+git12e3ed8 available.
> make: Entering directory '/workspace/Pai-Megatron-Patch-rocm/Megatron-LM-240126/megatron/core/datasets'
> make: Nothing to be done for 'default'.
> make: Leaving directory '/workspace/Pai-Megatron-Patch-rocm/Megatron-LM-240126/megatron/core/datasets'
> >>> done with dataset index builder. Compilation time: 0.086 seconds
> WARNING: constraints for invoking optimized fused softmax kernel are not met. We default back to unfused kernel invocations.
> > compiling and loading fused kernels ...
> /workspace/Pai-Megatron-Patch-rocm/megatron_patch/model/llava/clip_encoder.py:26: UserWarning: The cvcuda environment does not exist. Install cvcuda and use it
>   warnings.warn("The cvcuda environment does not exist. Install cvcuda and use it")
> /workspace/Pai-Megatron-Patch-rocm/megatron_patch/model/llava/clip_encoder.py:26: UserWarning: The cvcuda environment does not exist. Install cvcuda and use it
>   warnings.warn("The cvcuda environment does not exist. Install cvcuda and use it")
> INFO:datasets:PyTorch version 2.4.0a0+git12e3ed8 available.
> /workspace/Pai-Megatron-Patch-rocm/megatron_patch/model/llava/clip_encoder.py:26: UserWarning: The cvcuda environment does not exist. Install cvcuda and use it
>   warnings.warn("The cvcuda environment does not exist. Install cvcuda and use it")
> >>> done with compiling and loading fused kernels. Compilation time: 2.798 seconds
> time to initialize megatron (seconds): 9.282
> [after megatron is initialized] datetime: 2024-06-12 08:25:32
> > building MistralTokenizer tokenizer ...
> [rank1]: Traceback (most recent call last):
> [rank1]:   File "/workspace/Pai-Megatron-Patch-rocm/Megatron-LM-240126/megatron/core/transformer/spec_utils.py", line 99, in build_module
> [rank1]:     return module(
> [rank1]:   File "/workspace/Pai-Megatron-Patch-rocm/Megatron-LM-240126/megatron/core/fusions/fused_layer_norm.py", line 67, in __init__
> [rank1]:     assert (
> [rank1]: AssertionError: (RMSNorm) is not supported in FusedLayerNorm
> 
> [rank1]: During handling of the above exception, another exception occurred:
> 
> [rank1]: Traceback (most recent call last):
> [rank1]:   File "/workspace/Pai-Megatron-Patch-rocm/Megatron-LM-240126/megatron/core/transformer/spec_utils.py", line 99, in build_module
> [rank1]:     return module(
> [rank1]:   File "/workspace/Pai-Megatron-Patch-rocm/Megatron-LM-240126/megatron/core/transformer/transformer_layer.py", line 59, in __init__
> [rank1]:     self.input_layernorm = build_module(
> [rank1]:   File "/workspace/Pai-Megatron-Patch-rocm/Megatron-LM-240126/megatron/core/transformer/spec_utils.py", line 107, in build_module
> [rank1]:     raise type(e)(f"{str(e)} when instantiating {module.__name__}").with_traceback(
> [rank1]:   File "/workspace/Pai-Megatron-Patch-rocm/Megatron-LM-240126/megatron/core/transformer/spec_utils.py", line 99, in build_module
> [rank1]:     return module(
> [rank1]:   File "/workspace/Pai-Megatron-Patch-rocm/Megatron-LM-240126/megatron/core/fusions/fused_layer_norm.py", line 67, in __init__
> [rank1]:     assert (
> [rank1]: AssertionError: (RMSNorm) is not supported in FusedLayerNorm when instantiating FusedLayerNorm
>

**Comment by jerryli1981** [comment]
您好，打开TE应该就可以了，目前走的是Mcore中的local模式，所以不支持RMSNorm
