### ISSUE TITLE
qwen2 72b state_dict mismatch with TE

### ISSUE THREAD

**Issue by getao** [alibaba/Pai-Megatron-Patch#271]
用脚本转了qwen2 72b，不用TE转完可以跑，但loss一直在上升；但用TE转完直接就跑不起来load model的时候就开始各种报错(missing keys; unexpected keys，看了一下主要集中在layernorm的weight)

**Comment by jerryli1981** [comment]
您好，已经解决了，拉下最新的代码再重新测试下，谢谢

**Comment by getao** [comment]
> 您好，已经解决了，拉下最新的代码再重新测试下，谢谢

是解决了TE的问题，还是loss上升的问题啊？还是都解决了？

**Comment by getao** [comment]
> > 您好，已经解决了，拉下最新的代码再重新测试下，谢谢
> 
> 是解决了TE的问题，还是loss上升的问题啊？还是都解决了？

试了一下，都没解决。。。

**Comment by jerryli1981** [comment]
不应该啊，方便进群加下我私聊下吗？

**Comment by jerryli1981** [comment]
已解决，是代码版本的问题，更新到最新版就好了
