### ISSUE TITLE
Baichuan2 13B pretrain alibi_attn_mask   TP=2 pp=4 

### ISSUE THREAD

**Issue by cwszz** [alibaba/Pai-Megatron-Patch#29]
开发者你们好，我在落地该项目时发现，baichuan2 (num_head = 40) 在TP=2的时候 query_layer的num_head = 20, 而alibi_attn_mask = 40，请问是不是alibi_attn_mask没有进行 切分。 由于每个头的mask值都不同，所以存在报错。
对应代码部分： baichuan2/transformer.py/CoreAttention/forward 304行左右，attention_scores = attention_scores  + attention_mask。 （版本 Commit#26）
![image](https://github.com/alibaba/Pai-Megatron-Patch/assets/42961822/b20f83a6-d9d4-42a8-91e4-887e4fa8f760)

**Comment by jerryli1981** [comment]
您好，支持算子拆分（TP>1）的Alibi Masking我们内部正在抓紧研发中，它的难点不在于能否跑通，而是在于当设置TP>1时候的起始loss能否和TP=1不拆分的对齐。您感兴趣的话可以加入钉钉群我们进一步交流。

**Comment by jerryli1981** [comment]
我们现在能跑通TP=2但是会存在前向推理对不齐的现象，您那边如果有什么好的解决方案也欢迎提PR

**Comment by jerryli1981** [comment]
另外，13B模型在A/H100的80G显存不切分也是可以跑通的，所以在资源充足的情况下是暂时可以不用等待支持算子拆分的Alibi Masking功能上线。

**Comment by cwszz** [comment]
> 您好，支持算子拆分（TP>1）的Alibi Masking我们内部正在抓紧研发中，它的难点不在于能否跑通，而是在于当设置TP>1时候的起始loss能否和TP=1不拆分的对齐。您感兴趣的话可以加入钉钉群我们进一步交流。

首先，感谢您的回复。
1. 我目前的实验条件只是8 * 40G A100 （还想着尝试下13B full-para） 目前的参数是TP = 2, PP = 4; （因此需要考虑TP拆分，并且不太方便验证对齐性问题。）但我参考了 [Megatron-ds](https://github.com/bigscience-workshop/Megatron-DeepSpeed/blob/main/megatron/model/transformer.py#L116) 和 [Bloom](https://github.com/alibaba/Pai-Megatron-Patch/blob/main/megatron_patch/model/bloom/transformer.py) 这两个代码，目前看着还行，没办法做loss对齐的验证。

2. 此外关于在落地的过程中发现的小问题：
    (1). 构建数据集时，构建sample_idx时 在megatron/data/helpers.cpp 130行 remaining_seq_length = seq_length + 1 会导致sample_idx 之间长度 = seq + 1。
    (2). fp8_e4m3 和 fp8_hybrid 参数未指定。 
3.  最后请问 我在调通alibi_mask 后 40G * 8 A100，global bsz = 1， 只尝试了tp = 2, pp =4 和 tp = 4 pp = 2，这两种情况下均OOM。因为没有富裕的GPU，因此想问一下，如果全参数微调13B 不考虑zero 2/3的情况下，显存的消耗会有多大，单机情况下有能跑通的方案吗？

**Comment by jerryli1981** [comment]
> > 您好，支持算子拆分（TP>1）的Alibi Masking我们内部正在抓紧研发中，它的难点不在于能否跑通，而是在于当设置TP>1时候的起始loss能否和TP=1不拆分的对齐。您感兴趣的话可以加入钉钉群我们进一步交流。
> 
> 首先，感谢您的回复。
> 
> 1. 我目前的实验条件只是8 * 40G A100 （还想着尝试下13B full-para） 目前的参数是TP = 2, PP = 4; （因此需要考虑TP拆分，并且不太方便验证对齐性问题。）但我参考了 [Megatron-ds](https://github.com/bigscience-workshop/Megatron-DeepSpeed/blob/main/megatron/model/transformer.py#L116) 和 [Bloom](https://github.com/alibaba/Pai-Megatron-Patch/blob/main/megatron_patch/model/bloom/transformer.py) 这两个代码，目前看着还行，没办法做loss对齐的验证。
> 2. 此外关于在落地的过程中发现的小问题：
>    (1). 构建数据集时，构建sample_idx时 在megatron/data/helpers.cpp 130行 remaining_seq_length = seq_length + 1 会导致sample_idx 之间长度 = seq + 1。
>    (2). fp8_e4m3 和 fp8_hybrid 参数未指定。

hi，https://github.com/alibaba/Pai-Megatron-Patch/pull/33 看看这个PR，目前当TP>1时候的alibi mask的loss是对齐的
