### ISSUE TITLE
OSError: [Errno 28] No space left on device 请教

### ISSUE THREAD

**Issue by shyzzz521** [alibaba/Pai-Megatron-Patch#302]
4机微调qwen2_7b模型时，在
Running Encoding (num_proc=16):  25%|██▌       | 4007/16021 [08:08<29:33,  6.77 examples/s]
遇到错误：
[rank24]: multiprocess.pool.RemoteTraceback: 
[rank24]: """
[rank24]: Traceback (most recent call last):
[rank24]:   File "/home/jovyan/kys-workspace-zzzc/anaconda3/envs/megatron/lib/python3.10/site-packages/multiprocess/pool.py", line 125, in worker
[rank24]:     result = (True, func(*args, **kwds))
[rank24]:   File "/home/jovyan/kys-workspace-zzzc/anaconda3/envs/megatron/lib/python3.10/site-packages/datasets/utils/py_utils.py", line 614, in _write_generator_to_queue
[rank24]:     for i, result in enumerate(func(**kwargs)):
[rank24]:   File "/home/jovyan/kys-workspace-zzzc/anaconda3/envs/megatron/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 3489, in _map_single
[rank24]:     writer.write_batch(batch)
[rank24]:   File "/home/jovyan/kys-workspace-zzzc/anaconda3/envs/megatron/lib/python3.10/site-packages/datasets/arrow_writer.py", line 561, in write_batch
[rank24]:     self.write_table(pa_table, writer_batch_size)
[rank24]:   File "/home/jovyan/kys-workspace-zzzc/anaconda3/envs/megatron/lib/python3.10/site-packages/datasets/arrow_writer.py", line 579, in write_table
[rank24]:     self.pa_writer.write_table(pa_table, writer_batch_size)
[rank24]:   File "pyarrow/ipc.pxi", line 525, in pyarrow.lib._CRecordBatchWriter.write_table
[rank24]:   File "/home/jovyan/kys-workspace-zzzc/anaconda3/envs/megatron/lib/python3.10/site-packages/fsspec/implementations/local.py", line 369, in write
[rank24]:     return self.f.write(*args, **kwargs)
[rank24]: OSError: [Errno 28] No space left on device
[rank24]: """

有什么方法可以解决或避免吗？

应该不是磁盘存储的问题，磁盘数据空间还有6T

这是我的微调脚本：
pdsh -S -f 1024 -R ssh -w ^/home/jovyan/dataws1/magron/host_file/hostfile "cd /home/jovyan/dataws1/magron/Pai-Megatron-Patch/examples/qwen2 && bash megatron_run_finetune_qwen.sh dsw 7B 1 8 1e-5 1e-6 131072 131072 bf16 4 1 1 sel true true true true 200 /home/jovyan/dataws1/fine-wenshu/data/magron数据集/train_data_all.json /home/jovyan/dataws1/fine-wenshu/data/magron数据集/dev_data_all.json /home/jovyan/kys-workspace-zzzc/tmp/Qwen2-7B-Instruct-hf-to-mcore-te-tp4-pp1 6000 600 /home/jovyan/dataws1/models/wt_7b 2>&1 | tee -a /home/jovyan/dataws1/models/log/${RANK}-$(date "+%Y%m%d%H%M").log"

**Comment by CallmeZhangChenchen** [comment]
容器启动的时候有个  --shm-size 设置一下

在请教一下，在多机微调的时候，https://github.com/alibaba/Pai-Megatron-Patch/issues/307 有没有遇到过这个问题

**Comment by shyzzz521** [comment]
抱歉，看的晚了，没有遇到过这类问题，但看你已经解决了。

在设置参数之后还是会有这个错，查看下来是hfcache路径没有生效。现在切换到idxmap的方式跑了

**Comment by ltm920716** [comment]
> 容器启动的时候有个 --shm-size 设置一下
> 
> 在请教一下，在多机微调的时候，[#307](https://github.com/alibaba/Pai-Megatron-Patch/issues/307) 有没有遇到过这个问题

hi @CallmeZhangChenchen 
请问这个值的大小一般如何建议呀，我双机H100训练72B模型，shm-size设置的20g，还是会报这个错，数据加载和训练过程的nccl通信倒是没有问题，就是最后保存完模型会报错，是哪里会占用这个共享内存呢，谢谢
