### ISSUE TITLE
钉钉群满了

### ISSUE THREAD

**Issue by divisionblur** [alibaba/Pai-Megatron-Patch#304]
想进钉钉群

**Comment by lihaoling** [comment]
+1

**Comment by kangyishuai** [comment]
+1

**Comment by jerryli1981** [comment]
![image](https://github.com/user-attachments/assets/971cb8fd-f2ec-45ce-8a05-020dc57c62b9)

**Comment by jerryli1981** [comment]
试试这个二群

**Comment by jerryli1981** [comment]
https://github.com/alibaba/Pai-Megatron-Patch/pull/313
