### ISSUE TITLE
starcoder依赖哪个版本的megatron-lm？

### ISSUE THREAD

**Issue by bao-xiaoyi** [alibaba/Pai-Megatron-Patch#314]
如题，目前存在依赖问题。
另外，支持starcoder2吗

**Comment by bao-xiaoyi** [comment]
依赖问题已解决

**Comment by bao-xiaoyi** [comment]
此外，deepseekcoder-v2转换成megatron格式后（能够转换成功），模型参数量和deepseek-v2不一样导致训练加载模型失败。目前原因未知

**Comment by jerryli1981** [comment]
您好，有进一步的问题可以在群里发下deepseek-v2的错误提示哈
