### ISSUE TITLE
关于使用idxmap格式finetune qwen2

### ISSUE THREAD

**Issue by Gloid59** [alibaba/Pai-Megatron-Patch#319]
大数据集预处理时间过长，所以打算转成idxmap。我看到在commit #297中支持了这一功能，但之后#309中又转为使用新的finetune.py，其中仍然只支持原始格式数据集，是出于什么考虑呢？另外，commit #297版本的代码似乎也不能正常运行。

**Comment by jerryli1981** [comment]
您好，commit #297 的代码可以工作，如果你在微调的时候填写的seqlen和制作idxmap一样，那么这个布局就会错乱掉, 导致出现bug。你在实际微调的时候run finetune的时候需要将seqlen设置为制作idxmap的seqlen+1。我们在即将推出的llama3.1中取消了这个finetune和制作的seqlen长度不一致的问题。后续可以关注下。

**Comment by jerryli1981** [comment]
您好，已更新，烦请pull下最新的代码
