### ISSUE TITLE
mmap数据格式问题

### ISSUE THREAD

**Issue by bao-xiaoyi** [alibaba/Pai-Megatron-Patch#320]
https://github.com/alibaba/Pai-Megatron-Patch/blob/7289149b8450b7302a808956061b941ed6123548/toolkits/sft_data_preprocessing/build_idxmap_data.py#L55

十分感谢阿里团队提供megatron-patch，有几个问题想请教一下
问题1：为什么mmap数据还会加上padding？我理解的mmap的数据格式应该是这样：
![image](https://github.com/user-attachments/assets/c5f33c23-b135-4e3f-be2e-3050f418e93b)

问题2：加上padding的mmap数据，训练效率和LLamaRawDataset是不是一样？

问题3：想问问train-iters的问题，假如我想训练3个epoch。train-iters应该等于   数据量 * 3 / global batch，还是应该等于 token nums * 3 / （global batch * max length）？

**Comment by jerryli1981** [comment]
您好，问题1: 目前的方案暂时不支持多样本sequence packing，只是针对一条样本单独进行处理，mcore做流水并行的时候需要一个batch中的所有的样本长度是一样的，因此需要padding。问题2:会稍微快点，毕竟没有了分词的过程。3，是的
