### ISSUE TITLE
mcore 权重转换不支持pp>1

### ISSUE THREAD

**Issue by xs1997zju** [alibaba/Pai-Megatron-Patch#322]
1.examples里面llama, qwen的转mcore权重代码里面都不支持设置pp>1:
raise ValueError('not support pp convert')

2.转换权重为什么还需要用torchrun启动， 并且还初始化了一个megatron model来进行权重转换？

**Comment by divisionblur** [comment]
qwen2支持pp>1。

**Comment by jerryli1981** [comment]
嗯，qwen2是支持的，未来的llama3.1也是支持的
