### ISSUE TITLE
llava run error

### ISSUE THREAD

**Issue by yangzhipeng1108** [alibaba/Pai-Megatron-Patch#330]
cd /workspace/Pai-Megatron-Patch/examples/llava/
sh run_pretrain_megatron_llava.sh \
dsw  \
/workspace/Pai-Megatron-Patch  \
7B  \
4  \
32  \
1e-3  \
1e-4  \
2048  \
2048  \
0  \
bf16  \
1  \
1  \
sel  \
true   \
true  \
true   \
true   \
100000  \
/workspace/data/LLaVA-Pretrain/blip_laion_cc_sbu_558k.json  \
/workspace/model_ckpts/vicuna-7b-v1.5-to-mg-tp1-pp1  \
10000000000  \
100000000  \
/workspace/output_patch_test

![image](https://github.com/user-attachments/assets/81806e72-8cb3-496c-a748-5d81d27db41e)

**Comment by jerryli1981** [comment]
您好，在run_pretrain_megatron_llava.sh下面加一个--dataset LLava-Pretrain-Raw 试试

**Comment by yangzhipeng1108** [comment]
![image](https://github.com/user-attachments/assets/34b03941-567e-4f3f-8c97-0c9c70f35300)
![image](https://github.com/user-attachments/assets/51a3b782-6c73-4b65-8487-72ca9011879f)

**Comment by hxmzy520** [comment]
我也遇到过同样的问题， 请问/workspace/model_ckpts/vicuna-7b-v1.5-to-mg-tp1-pp1是使用什么脚本转换的？

**Comment by yangzhipeng1108** [comment]
> 我也遇到过同样的问题， 请问/workspace/model_ckpts/vicuna-7b-v1.5-to-mg-tp1-pp1是使用什么脚本转换的？

llama2
