### ISSUE TITLE
关于llava适配的问题

### ISSUE THREAD

**Issue by divisionblur** [alibaba/Pai-Megatron-Patch#333]
llava好像不支持保存 projection 那两个矩阵。

**Comment by divisionblur** [comment]
另外，有对qwen2-vl适配的打算吗？

**Comment by divisionblur** [comment]
llava求loss的时候图像特征embedding最后一个需要和文本的第一个embedding求loss吗？

**Comment by Derek-Kun** [comment]
兄弟，我们碰到这个问题了，只训练projector后好像没保存任何东西，请问你是怎么解决的？
