### ISSUE TITLE
有适配qwen2-vl的打算吗？

### ISSUE THREAD

**Issue by divisionblur** [alibaba/Pai-Megatron-Patch#339]
如题，大佬们接下来有适配qwen2-vl的计划吗？感觉最近这个很火

**Comment by jerryli1981** [comment]
目前在代码库中可以找到我们去年接入的llava和qwen-vl-1.0版本，目前看多模态大模型性能有较大幅度的改善，我们正在考虑重构下整个qwen-vl的最佳实践以满足用户需求

**Comment by divisionblur** [comment]
> 目前在代码库中可以找到我们去年接入的llava和qwen-vl-1.0版本，目前看多模态大模型性能有较大幅度的改善，我们正在考虑重构下整个qwen-vl的最佳实践以满足用户需求

哥，这个开始弄了吗？
