### ISSUE TITLE
建议对deepseek-v2-coder-lite进行sft测试

### ISSUE THREAD

**Issue by bao-xiaoyi** [alibaba/Pai-Megatron-Patch#342]
sft训练后，生成代码容易产生明显语法错误，与抽风问题。目前尚未查明原因

**Comment by jerryli1981** [comment]
您好，试试在微调的时候加一个--reset-attention-mask

**Comment by jerryli1981** [comment]
您好，整个SFT系统我们已经升级，辛苦再试试

**Comment by bao-xiaoyi** [comment]
重新尝试过了，问题依然存在，有非常明显的语法错误。
此外，对新的deepseek的sft pipline来说，同样存在不会正常终止的问题，eos token没有被正常训练进去。

**Comment by bao-xiaoyi** [comment]
相同的数据，qwen2.5-coder-7b训练效果正常，和deepseek差异非常大

**Comment by jerryli1981** [comment]
您好，我们重新校验了下所有的tokenizer发现只有deepseek这个没有添加padding_side='right', 实在抱歉啊，我们通过一个PR修复了下，您看看哈：https://github.com/alibaba/Pai-Megatron-Patch/pull/370
