### ISSUE TITLE
llama7b OOM问题

### ISSUE THREAD

**Issue by mxjmtxrm** [alibaba/Pai-Megatron-Patch#343]
请问在get model的时候，ddp之后显存占用会增加一倍[https://github.com/NVIDIA/Megatron-LM/blob/f7727433293427bef04858f67b2889fe9b177d88/megatron/training.py#L299](DDP)？

**Comment by lostkevin** [comment]
理论上ddp会创建一个ParamAndGradBuffer, 大约会导致占用x2/x3

以bf16为例
DDP前：仅模型参数 2M
DDP后：模型参数2M+梯度 4M=6M

**Comment by mxjmtxrm** [comment]
明白了，谢谢
