### ISSUE TITLE
在转换模型的时候就报了一些bug

### ISSUE THREAD

**Issue by Yanhong-Li** [alibaba/Pai-Megatron-Patch#350]
Bug1: 参数冲突
![image](https://github.com/user-attachments/assets/5205403c-739f-41f1-bde6-4984e543f7dd)

Bug2：手动改了第一个bug之后又报了第二个
![image](https://github.com/user-attachments/assets/984d9a33-a84d-4a78-bb69-c33920565a18)

**Comment by echo-valor** [comment]
这个问题怎么解决的
