### ISSUE TITLE
Possible bug in Mistral MCore <->HF Model conversions because of _extra_state layers

### ISSUE THREAD

**Issue by abgoswam** [alibaba/Pai-Megatron-Patch#363]
**HF to MCore**
- drops the `_extra_state` layers
- https://github.com/alibaba/Pai-Megatron-Patch/blob/4b6c687aa07ee933da950a88c6c2b8ad2c79d0d9/toolkits/model_checkpoints_convertor/mistral/hf2mcore.py#L384-L385

**MCore to HF**
- does strict check, hence fails 
- https://github.com/alibaba/Pai-Megatron-Patch/blob/4b6c687aa07ee933da950a88c6c2b8ad2c79d0d9/toolkits/model_checkpoints_convertor/mistral/hf2mcore.py#L284

Possible Workarounds:
1. keep the `_extra_state` layers OR
2. when loading specify  `strict=False`  e.g.  `model.load_state_dict(state_dict, strict=False)`

**Comment by jerryli1981** [comment]
thank you very much. currently, we use workaround 2 to solve.
