### ISSUE TITLE
最新的commit bf582d8f30d8ffbba51db3dcda984c9f0261d57d 有num_seq None的问题

### ISSUE THREAD

**Issue by WuNein** [alibaba/Pai-Megatron-Patch#374]
<img width="429" alt="3f5cce46c9a6c26262516afd3152322" src="https://github.com/user-attachments/assets/27f59649-c6b3-4101-9fdb-b3a30b640e08">

我脚本已经加入了这个选项

<img width="542" alt="46cc3b4b71aa777765a9f0d30668822" src="https://github.com/user-attachments/assets/9d3dfa6f-357f-4e87-9d30-c2b7a1e12bd1">

但是num_seq显示None训练出错，这个就是最新更改的代码导致的。

老的commit没有任何问题。
![image](https://github.com/user-attachments/assets/a9259be4-8d7e-4f7b-8e32-e27640400cbe)

训练环境是8卡H100，使用提供的镜像和FA3+FP8

**Comment by WuNein** [comment]
我训练使用了pretrain + mmap 
https://github.com/alibaba/Pai-Megatron-Patch/blob/bf582d8f30d8ffbba51db3dcda984c9f0261d57d/examples/qwen2/pretrain_qwen.py#L115

我认为是这个也需要num_seq否者预训练没法做了

**Comment by WuNein** [comment]
问一下CPT阶段是否能提供序列拼接~

**Comment by zheng-kuaishou** [comment]
遇到同样的问题

**Comment by lostkevin** [comment]
预训练应该没有序列拼接的概念，可以先看一下binmap数据是怎么构造的

**Comment by WuNein** [comment]
> 预训练应该没有序列拼接的概念，可以先看一下binmap数据是怎么构造的

关键是现在正常的预训练就跑不通，会碰到nun seq问题
