### ISSUE TITLE
qwen2 moe 模型在开启grouped gemm报'NoneType' object has no attribute 'linear_fc1' when instantiating MoELayer when instantiating TransformerLayer

### ISSUE THREAD

**Issue by jamindy** [alibaba/Pai-Megatron-Patch#387]
qwen2 moe模型在--moe-grouped-gemm开启grouped gemm报错如下：

[rank5]:   File "/xx/xx/Pai-Megatron-Patch/examples/qwen2/pretrain_qwen.py", line 276, in <module>
[rank5]:     pretrain(
[rank5]:   File "/xx/xx/Pai-Megatron-Patch/PAI-Megatron-LM-240718/megatron/training/training.py", line 266, in pretrain
[rank5]:     model, optimizer, opt_param_scheduler = setup_model_and_optimizer(model_provider, model_type)
[rank5]:   File "/xx/xx/Pai-Megatron-Patch/PAI-Megatron-LM-240718/megatron/training/training.py", line 600, in setup_model_and_optimizer
[rank5]:     model = get_model(model_provider_func, model_type)
[rank5]:   File "/xx/xx/Pai-Megatron-Patch/PAI-Megatron-LM-240718/megatron/training/training.py", line 467, in get_model
[rank5]:     model = model_provider_func(pre_process=pre_process, post_process=post_process)
[rank5]:   File "/xx/xx/Pai-Megatron-Patch/examples/qwen2/pretrain_qwen.py", line 66, in model_provider
[rank5]:     model = GPTModel(
[rank5]:   File "/xx/xx/Pai-Megatron-Patch/megatron_patch/model/qwen2/model.py", line 108, in __init__
[rank5]:     self.decoder = TransformerBlock(
[rank5]:   File "/xx/xx/Pai-Megatron-Patch/megatron_patch/model/qwen2/transformer_block.py", line 154, in __init__
[rank5]:     self._build_layers()
[rank5]:   File "/xx/xx/Pai-Megatron-Patch/megatron_patch/model/qwen2/transformer_block.py", line 169, in _build_layers
[rank5]:     [
[rank5]:   File "/xx/xx/Pai-Megatron-Patch/megatron_patch/model/qwen2/transformer_block.py", line 170, in <listcomp>
[rank5]:     build_layer(layer_spec, i + 1)
[rank5]:   File "/xx/xx/Pai-Megatron-Patch/megatron_patch/model/qwen2/transformer_block.py", line 165, in build_layer
[rank5]:     return build_module(layer_spec, config=self.config, layer_number=layer_number,)
[rank5]:   File "/xx/xx/Pai-Megatron-Patch/PAI-Megatron-LM-240718/megatron/core/transformer/spec_utils.py", line 107, in build_module
[rank5]:     raise type(e)(f"{str(e)} when instantiating {module.__name__}").with_traceback(
[rank5]:   File "/xx/xx/Pai-Megatron-Patch/PAI-Megatron-LM-240718/megatron/core/transformer/spec_utils.py", line 99, in build_module
[rank5]:     return module(
[rank5]:   File "/xx/xx/Pai-Megatron-Patch/megatron_patch/model/qwen2/transformer_layer.py", line 128, in __init__
[rank5]:     self.mlp = build_module(submodules.mlp, config=self.config)
[rank5]:   File "/xx/xx/Pai-Megatron-Patch/PAI-Megatron-LM-240718/megatron/core/transformer/spec_utils.py", line 107, in build_module
[rank5]:     raise type(e)(f"{str(e)} when instantiating {module.__name__}").with_traceback(
[rank5]:   File "/xx/xx/Pai-Megatron-Patch/PAI-Megatron-LM-240718/megatron/core/transformer/spec_utils.py", line 99, in build_module
[rank5]:     return module(
[rank5]:   File "/xx/xx/Pai-Megatron-Patch/megatron_patch/model/qwen2/moe/moe_layer.py", line 87, in __init__
[rank5]:     self.shared_expert = MLP(self.config, submodules, is_expert=False, is_shared_expert=True)
[rank5]:   File "/xx/xx/Pai-Megatron-Patch/megatron_patch/model/qwen2/transformer/mlp.py", line 84, in __init__
[rank5]:     submodules.linear_fc1,
[rank5]: AttributeError: 'NoneType' object has no attribute 'linear_fc1' when instantiating MoELayer when instantiating TransformerLayer

**Comment by jerryli1981** [comment]
https://github.com/alibaba/Pai-Megatron-Patch/pull/388
