### ISSUE TITLE
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/None/resolve/main/tokenizer_config.json

### ISSUE THREAD

**Issue by XCD4P** [alibaba/Pai-Megatron-Patch#398]
when i tried to train deepseek, without --load config, it will throw this error.

**Comment by lostkevin** [comment]
You should provide local pretrained ckpt path to load tokenizer

**Comment by XCD4P** [comment]
> You should provide local pretrained ckpt path to load tokenizer

I added a parameter hf-tokenizer-path to load the tokenizer from a local path, it works. thanks
