### ISSUE TITLE
多机多卡相关

### ISSUE THREAD

**Issue by gllary** [alibaba/Pai-Megatron-Patch#53]
目前看到的示例是单机多卡的，想请教一下大佬们，如果想运行多级多卡实验应该怎么配置呢？

**Comment by jerryli1981** [comment]
您好，可以参考这篇文档https://www.aliyun.com/solution/tech-solution/pai_lingjun  也可以加入钉钉群

**Comment by jamestch** [comment]
> 示例是单机多卡的，想请教一下大佬们，如果想运行多级多

这个是依赖于阿里云的计算资源环境的，有基于公司内部算力资源（比如A100组成的集群）的多机多卡训练配置教程吗？
