### ISSUE TITLE
百川2 的max-z loss，为啥代码里只有前向部分，没有反向部分？

### ISSUE THREAD

**Issue by flower-with-safe** [alibaba/Pai-Megatron-Patch#54]
我们团队自己实现了一个，可以一起讨论一下：
https://github.com/baichuan-inc/Baichuan2/issues/220

**Comment by jerryli1981** [comment]
好的，收到。可以加入钉钉群，然后加下我的钉钉，我们一起开个小群聚焦下max z loss

**Comment by butterluo** [comment]
> 我们团队自己实现了一个，可以一起讨论一下： [baichuan-inc/Baichuan2#220](https://github.com/baichuan-inc/Baichuan2/issues/220)

貌似你forward的实现和baichuan2原版的实现不一样?

**Comment by flower-with-safe** [comment]
> > 我们团队自己实现了一个，可以一起讨论一下： [baichuan-inc/Baichuan2#220](https://github.com/baichuan-inc/Baichuan2/issues/220)
> 
> 貌似你forward的实现和baichuan2原版的实现不一样?

哪里不一样了呀？
