### ISSUE TITLE
使用huggingface + deepspeed stage 3训练codellama 报错，stage2 可以，这是为什么？

### ISSUE THREAD

**Issue by weilanzhikong** [alibaba/Pai-Megatron-Patch#66]
assert param.ds_status == ZeroParamStatus.AVAILABLE, param.ds_summary()
AssertionError: {'id': 1247, 'status': 'NOT_AVAILABLE', 'numel': 0, 'ds_numel': 0, 'shape': (0,), 'ds_shape': (0, 5120), 'requires_grad': True, 'grad_shape': None, 'persist': True, 'active_sub_modules': {565}, 'ds_tensor.shape': torch.Size([0])}

**Comment by lwmlyy** [comment]
zero3目前支持不太好，且训练效率比较低，建议切换到megatron训练
